name: CI CD Pipeline for Rasa Model
on:
  push:
    branches:
    - main
    paths:
    - 'data/**'
    - 'config.yml'
    - 'domain.yml'

env:
  DOMAIN: ${{ secrets.DOMAIN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RASA_X_USERNAME: ${{ secrets.RASA_X_USERNAME }}
  RASA_X_PASSWORD: ${{ secrets.RASA_X_PASSWORD }}
  RASA_X_TOKEN: ${{ secrets.RASA_X_TOKEN }}

jobs:
  
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 2days

  build-model:
    name: Build Model
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<20"
        pip install protobuf==3.19.4
        pip install rasa[full]==3.1.2
    - name: Train model
      run: |
        rasa train
    - name: Upload model
      if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/main')
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: models

  upload-model:
    name: Upload the trained model to Rasa X
    needs:
    - build-model
    env:
      MODEL_DIRECTORY: "models"

    if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
    - name: Download Model
      uses: actions/download-artifact@v2
      with:
        name: model
        path: ${{ env.MODEL_DIRECTORY }}

    - name: Get path to model
      run: |
        ls -R
        echo "MODELNAME=${{ env.MODEL_DIRECTORY }}/$(ls ${{ env.MODEL_DIRECTORY }})" >> $GITHUB_ENV
    - name: Upload Model to Rasa
      run: |

        curl -k -F "model=@${MODELNAME}" "https://${{ env.DOMAIN }}/api/projects/default/models?api_token=48b1ccf781eb0a6f636551d2414adcb000c08e3c"